version: "3"

services:
    
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

    volumes:
      - ./data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    links :
      - "db"

  node:
    
    restart: always 
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links :
      - "db"

volumes:
  my-datavolume:


    
